site:
  name: Documentation

  locales: [en]

  seo_title: LocomotiveCMS - Documentation
  meta_keywords: "some meta keywords"
  meta_description: "some meta description"

  pages:
    - "index": # page path (the template can edited here app/views/pages/index.liquid)
        title: "Home page"
        published: true
    - "404":
        title: "Page not found"
        published: true

    - "installation":
        title: "Installation guide"
        listed: true
        published: true
        redirect_url: "/installation/requirements"
    - "installation/requirements":
        listed: true
    - "installation/getting_started":
        listed: true
    - "installation/heroku":
        title: "Heroku hosting"
        listed: true
    - "installation/developers":
        title: "For developers"
        listed: true

    - "guides":
        title: "Guides"
        listed: true
        redirect_url: "guides/multisites"
    - "guides/multisites":
        title: "Multi-sites"
        listed: true
    - "guides/upgrade_v1":
        title: "Upgrade to 2.0"
        listed: true

    - "editor":
        title: "Editor"
        listed: true
        redirect_url: "editor/installation"

    - "editor/installation":
        listed: true
    - "editor/create_a_site":
        listed: true
    - "editor/deployment":
        listed: true
    - "editor/site_templates":
        listed: true

    - "templates":
        title: "Templates"
        listed: true
        redirect_url: "/templates/basics"
    - "templates/basics":
        listed: true
    - "templates/objects":
        listed: true
    - "templates/filters":
        listed: true
    - "templates/tags":
        listed: true
